### PR TITLE
Update Season on README.md

### PR DESCRIPTION
**Pull request by foehammer127-svg**
I just updated what season it was. ;)

### CODE REVIEW

**Review by PatrickSedlacek — APPROVED** [review]
Looks accurate to me. Doesn't break existing README

**Comment by REM-Codes** [comment]
Mine didn't break the existing readme either...

**Comment by ftc19567** [comment]
Got it!

**Comment by texasdiaz** [comment]
This content is auto-generated. It is not to be edited manually. We appreciate your suggestions and good will, but I'm afraid we cannot accept your PR to this repo. We thank you for your understanding and your patience.

**Pull request closed without merging**
